### ISSUE TITLE
Analyze button

### ISSUE THREAD

**Issue by nishapp** [watson-developer-cloud/personality-insights-nodejs#108]
Hi,

I tried to deploy the code using Bluemix account and the analyze button does not work. 

https://we-retail-fashion.eu-gb.mybluemix.net/

Any idea ?

Regards,

nishant

**Comment by neil-boyette-ibm** [comment]
Some general questions; did you follow all the instructions? Configured the right credentials and instances of the services in BlueMix etc?

Without access to your code, or a more specific error, its a bit hard for me to give you more specifics (apart from the general and unhelpful that it works for us :-) ).

**Comment by nishadobe** [comment]
Hey Neil. 

Thanks for your reply. I just deployed the code via bluemix and I have used my code. Can you please let me know how to get a specific code. IF you see the link I provided the analyse button is disabled for some reason. 

Thanks.

**Comment by nishadobe** [comment]
This is what I have in code. 

---
declared-services:
  personality-insights-service:
    label: personality_insights
    plan: tiered
applications:
  name: personality-insights-nodejs-pithia-2246
  command: npm start
  path: .
  memory: 512M
  instances: 1
  services:
    - personality-insights-service
  env:
    NODE_ENV: production
  host: personality-insights-nodejs-pithia-2246

**Comment by AlexandrosPas** [comment]
Show us your credentials.json file:

'{
  "personality_insights" : {
    "password": "<password>",
    "username": "<username>",
    "version": "v2",
    "headers": {
      "X-Watson-Learning-Opt-Out": 1
    }
  },

  "twitter" : {
    "application": {
      "consumer_key" : "<consumer_key>",
      "consumer_secret" : "<consumer_secret>"
    },
    "credentials": []
  }
}'

**Comment by PhilippeComte** [comment]
Hello , 
getting the same issue trying to run the app locally
The install thru npm install shows error but I don't know whether they are critical or not
Does it work for you on local ? 

PCMacBook-Pro:personality-insights-nodejs-master philippecomte$ npm install
npm WARN package.json Dependency 'dotenv' exists in both dependencies and devDependencies, using 'dotenv@^2.0.0' from dependencies
npm WARN deprecated nodejs-twitter-crawler@0.10.3: WARNING: This project has been renamed to twitter-crawler. Install using twitter-crawler instead.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
 
> websocket@1.0.23 install /Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/PersonalityInsights/personality-insights-nodejs-master/node_modules/watson-developer-cloud/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
 
> execSync@1.0.2 install /Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/PersonalityInsights/personality-insights-nodejs-master/node_modules/codecov/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
 
> typechecker@2.0.8 preinstall /Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/PersonalityInsights/personality-insights-nodejs-master/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

 
> typechecker@2.0.8 preinstall /Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/PersonalityInsights/personality-insights-nodejs-master/node_modules/i18n/node_modules/messageformat/node_modules/watchr/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

**Comment by AlexandrosPas** [comment]
I've found the issue with the disabled analyze button. I will explain:

From what I understand captcha made sunburst crash from[ Issue#107](https://github.com/watson-developer-cloud/personality-insights-nodejs/issues/107) but the developers never revoked to the last stable version. So for now search for the index.ejs file in the /views folder.

Find the lines that build the buttons, and delete the disabled notation
` 		
<button type="submit" disabled class="base--button input--submit-button1">Analyze</button>
` 

I'm trying to fix the captcha issue but this will do for now.

**Comment by nishadobe** [comment]
I am trying to edit and save but getting this message. 

"while parsing a block mapping; expected <block end>, but found BlockMappingStart; in 'reader', line 8, column 3: command: npm start ^"

**Comment by nishadobe** [comment]
Getting captcha error now
<img width="1036" alt="screen shot 2016-10-14 at 11 10 55" src="https://cloud.githubusercontent.com/assets/18189472/19382108/fdcb3e20-91fe-11e6-9358-37e699e4fece.png">

**Comment by AlexandrosPas** [comment]
It's impossible that your button isn't still activated after what i suggested. (from what i see thanks to your screenshot)
In order to edit the `index.ejs` use any local editor (Notepad++). Save the file and redo the steps of Cloud Foundry to push your project again in Bluemix.

Other suggestion (worked for me): 
1)Download the master code from github.
2)Replace the files `index.ejs` and `header.ejs` which you will download (or copy-paste) from germanattanasio-patch-1 branch (not master that is).
3)Open a `cmd` and navigate through your project folder (where `manifest.yml` file is located).
4)Login to Bluemix and `push` the project (as described in the `README.MD`)

Hope this helps

**Comment by nishadobe** [comment]
Thanks it works!
