### ISSUE TITLE
Watson Personality Insights API is providing summary for a input text consisting of just numbers.

### ISSUE THREAD

**Issue by Aathiabitha** [watson-developer-cloud/personality-insights-nodejs#89]
I was testing Watson Personality Insights API as a part of my application and found that when user provides an input text that consists of just numbers, Instead of error message, Watson is giving a proper summary back to the user.

It questions the credibility of watson on its understanding of the input text. 

Please find the attached input text used for testing.

[Watson_Personality Insights_Input Text_Numbers.txt](https://github.com/watson-developer-cloud/personality-insights-nodejs/files/244610/Watson_Personality.Insights_Input.Text_Numbers.txt)

**Comment by herchu** [comment]
Thank you. We are looking into this issue.

**Comment by neil-boyette-ibm** [comment]
You have a good point, in that it indeed looks bad, even though it is technically is a correct response. 

One of the (many) ways we categorize the words, is numeric. So, having text that only has numbers, is just as valid as text which for instance only has angry words, even though both will provide a skewed profile. While technically correct, the service should be checking the input text to see if it is highly concentrated in a single type of word, and if so either provide and error or a warning.

I'll update this issue once the service has been updated accordingly (once we define the boundaries to check for).

**Comment by Aathiabitha** [comment]
Thank you Neil.  If you like you can update me in my IBM id - Aathiabitha Patteaswaran/India/IBM@IBMIN

**Comment by germanattanasio** [comment]
@neil-boyette-ibm is the task complete ?

**Comment by neil-boyette-ibm** [comment]
Not yet, we have it in the queue but is lower priority at this time as the issue is more complicated than it first appears (and is also a corner case that in practice won't happen much, if at all). 

In short, numerics are valid inputs and you could provide text which maps to just a single category. We don't want to just hard code a warning message for this one case, instead we need to do some research to define in which cases the too-small a number of categories the provided text mapped to, creates profiles created would not be statistically valid.

**Comment by nfriedly** [comment]
Since this is a service-level thing and not specific to the demo, I'm going to close the ticket here.
